#server configuration
server:
  port: 8081
  servlet:
    context-path: /api/v1

#spring configuration
spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/hastane

#jpa configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#banner mode of
  main:
    banner-mode: off